// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"jike_server/internal/biz"
	"jike_server/internal/conf"
	"jike_server/internal/data"
	"jike_server/internal/pkg/auth"
	"jike_server/internal/server"
	"jike_server/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData, logger)
	jwt := provideJWT(auth)
	accountUsecase := biz.NewAccountUsecase(accountRepo, jwt, logger)
	accountService := service.NewAccountService(accountUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, accountService, jwt, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// 提供 JWT 实例
func provideJWT(authConf *conf.Auth) *auth.JWT {
	return auth.NewJWT(authConf.Jwt.Secret, authConf.Jwt.Issuer, authConf.Jwt.ExpiresIn)
}
