// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/account/v1/account.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AuthorizationsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthorizationsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthorizationsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthorizationsReqMultiError, or nil if none found.
func (m *AuthorizationsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthorizationsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetMobile()) != 11 {
		err := AuthorizationsReqValidationError{
			field:  "Mobile",
			reason: "value length must be 11 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if utf8.RuneCountInString(m.GetCode()) != 6 {
		err := AuthorizationsReqValidationError{
			field:  "Code",
			reason: "value length must be 6 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if len(errors) > 0 {
		return AuthorizationsReqMultiError(errors)
	}

	return nil
}

// AuthorizationsReqMultiError is an error wrapping multiple validation errors
// returned by AuthorizationsReq.ValidateAll() if the designated constraints
// aren't met.
type AuthorizationsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthorizationsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthorizationsReqMultiError) AllErrors() []error { return m }

// AuthorizationsReqValidationError is the validation error returned by
// AuthorizationsReq.Validate if the designated constraints aren't met.
type AuthorizationsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthorizationsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthorizationsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthorizationsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthorizationsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthorizationsReqValidationError) ErrorName() string {
	return "AuthorizationsReqValidationError"
}

// Error satisfies the builtin error interface
func (e AuthorizationsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthorizationsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthorizationsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthorizationsReqValidationError{}

// Validate checks the field values on AuthorizationsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthorizationsResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthorizationsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthorizationsRespMultiError, or nil if none found.
func (m *AuthorizationsResp) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthorizationsResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for ExpiresAt

	// no validation rules for UserId

	// no validation rules for Mobile

	// no validation rules for Nickname

	if len(errors) > 0 {
		return AuthorizationsRespMultiError(errors)
	}

	return nil
}

// AuthorizationsRespMultiError is an error wrapping multiple validation errors
// returned by AuthorizationsResp.ValidateAll() if the designated constraints
// aren't met.
type AuthorizationsRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthorizationsRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthorizationsRespMultiError) AllErrors() []error { return m }

// AuthorizationsRespValidationError is the validation error returned by
// AuthorizationsResp.Validate if the designated constraints aren't met.
type AuthorizationsRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthorizationsRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthorizationsRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthorizationsRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthorizationsRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthorizationsRespValidationError) ErrorName() string {
	return "AuthorizationsRespValidationError"
}

// Error satisfies the builtin error interface
func (e AuthorizationsRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthorizationsResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthorizationsRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthorizationsRespValidationError{}

// Validate checks the field values on GetAccountReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAccountReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAccountReqMultiError, or
// nil if none found.
func (m *GetAccountReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetAccountReqMultiError(errors)
	}

	return nil
}

// GetAccountReqMultiError is an error wrapping multiple validation errors
// returned by GetAccountReq.ValidateAll() if the designated constraints
// aren't met.
type GetAccountReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountReqMultiError) AllErrors() []error { return m }

// GetAccountReqValidationError is the validation error returned by
// GetAccountReq.Validate if the designated constraints aren't met.
type GetAccountReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountReqValidationError) ErrorName() string { return "GetAccountReqValidationError" }

// Error satisfies the builtin error interface
func (e GetAccountReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountReqValidationError{}

// Validate checks the field values on GetAccountResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAccountResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAccountRespMultiError,
// or nil if none found.
func (m *GetAccountResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Birthday

	// no validation rules for Gender

	// no validation rules for Id

	// no validation rules for Mobile

	// no validation rules for Nickname

	// no validation rules for Avatar

	if len(errors) > 0 {
		return GetAccountRespMultiError(errors)
	}

	return nil
}

// GetAccountRespMultiError is an error wrapping multiple validation errors
// returned by GetAccountResp.ValidateAll() if the designated constraints
// aren't met.
type GetAccountRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountRespMultiError) AllErrors() []error { return m }

// GetAccountRespValidationError is the validation error returned by
// GetAccountResp.Validate if the designated constraints aren't met.
type GetAccountRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountRespValidationError) ErrorName() string { return "GetAccountRespValidationError" }

// Error satisfies the builtin error interface
func (e GetAccountRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountRespValidationError{}
