// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/account/v1/account.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationsReq) Reset() {
	*x = AuthorizationsReq{}
	mi := &file_api_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationsReq) ProtoMessage() {}

func (x *AuthorizationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationsReq.ProtoReflect.Descriptor instead.
func (*AuthorizationsReq) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationsReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AuthorizationsReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AuthorizationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationsResp) Reset() {
	*x = AuthorizationsResp{}
	mi := &file_api_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationsResp) ProtoMessage() {}

func (x *AuthorizationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationsResp.ProtoReflect.Descriptor instead.
func (*AuthorizationsResp) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationsResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthorizationsResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AuthorizationsResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthorizationsResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AuthorizationsResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GetAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountReq) Reset() {
	*x = GetAccountReq{}
	mi := &file_api_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountReq) ProtoMessage() {}

func (x *GetAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountReq.ProtoReflect.Descriptor instead.
func (*GetAccountReq) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{2}
}

type GetAccountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Birthday      string                 `protobuf:"bytes,1,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender        int32                  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResp) Reset() {
	*x = GetAccountResp{}
	mi := &file_api_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResp) ProtoMessage() {}

func (x *GetAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResp.ProtoReflect.Descriptor instead.
func (*GetAccountResp) Descriptor() ([]byte, []int) {
	return file_api_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResp) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *GetAccountResp) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetAccountResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAccountResp) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetAccountResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetAccountResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_api_account_v1_account_proto protoreflect.FileDescriptor

const file_api_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1capi/account/v1/account.proto\x12\n" +
	"account.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"S\n" +
	"\x11AuthorizationsReq\x12 \n" +
	"\x06mobile\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12\x1c\n" +
	"\x04code\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x06R\x04code\"\x96\x01\n" +
	"\x12AuthorizationsResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\"\x0f\n" +
	"\rGetAccountReq\"\xa0\x01\n" +
	"\x0eGetAccountResp\x12\x1a\n" +
	"\bbirthday\x18\x01 \x01(\tR\bbirthday\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\x05R\x06gender\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar2\xdc\x01\n" +
	"\aAccount\x12n\n" +
	"\x0eAuthorizations\x12\x1d.account.v1.AuthorizationsReq\x1a\x1e.account.v1.AuthorizationsResp\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/authorizations\x12a\n" +
	"\x0eGetAccountInfo\x12\x19.account.v1.GetAccountReq\x1a\x1a.account.v1.GetAccountResp\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/user/profileB\x1fZ\x1djike_server/api/account/v1;v1b\x06proto3"

var (
	file_api_account_v1_account_proto_rawDescOnce sync.Once
	file_api_account_v1_account_proto_rawDescData []byte
)

func file_api_account_v1_account_proto_rawDescGZIP() []byte {
	file_api_account_v1_account_proto_rawDescOnce.Do(func() {
		file_api_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_account_v1_account_proto_rawDesc), len(file_api_account_v1_account_proto_rawDesc)))
	})
	return file_api_account_v1_account_proto_rawDescData
}

var file_api_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_account_v1_account_proto_goTypes = []any{
	(*AuthorizationsReq)(nil),  // 0: account.v1.AuthorizationsReq
	(*AuthorizationsResp)(nil), // 1: account.v1.AuthorizationsResp
	(*GetAccountReq)(nil),      // 2: account.v1.GetAccountReq
	(*GetAccountResp)(nil),     // 3: account.v1.GetAccountResp
}
var file_api_account_v1_account_proto_depIdxs = []int32{
	0, // 0: account.v1.Account.Authorizations:input_type -> account.v1.AuthorizationsReq
	2, // 1: account.v1.Account.GetAccountInfo:input_type -> account.v1.GetAccountReq
	1, // 2: account.v1.Account.Authorizations:output_type -> account.v1.AuthorizationsResp
	3, // 3: account.v1.Account.GetAccountInfo:output_type -> account.v1.GetAccountResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_account_v1_account_proto_init() }
func file_api_account_v1_account_proto_init() {
	if File_api_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_account_v1_account_proto_rawDesc), len(file_api_account_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_account_v1_account_proto_goTypes,
		DependencyIndexes: file_api_account_v1_account_proto_depIdxs,
		MessageInfos:      file_api_account_v1_account_proto_msgTypes,
	}.Build()
	File_api_account_v1_account_proto = out.File
	file_api_account_v1_account_proto_goTypes = nil
	file_api_account_v1_account_proto_depIdxs = nil
}
