// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/article/v1/article.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetArticleChannelReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArticleChannelReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleChannelReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleChannelReqMultiError, or nil if none found.
func (m *GetArticleChannelReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleChannelReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetArticleChannelReqMultiError(errors)
	}

	return nil
}

// GetArticleChannelReqMultiError is an error wrapping multiple validation
// errors returned by GetArticleChannelReq.ValidateAll() if the designated
// constraints aren't met.
type GetArticleChannelReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleChannelReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleChannelReqMultiError) AllErrors() []error { return m }

// GetArticleChannelReqValidationError is the validation error returned by
// GetArticleChannelReq.Validate if the designated constraints aren't met.
type GetArticleChannelReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleChannelReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleChannelReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleChannelReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleChannelReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleChannelReqValidationError) ErrorName() string {
	return "GetArticleChannelReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleChannelReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleChannelReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleChannelReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleChannelReqValidationError{}

// Validate checks the field values on ArticleChannel with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ArticleChannel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArticleChannel with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ArticleChannelMultiError,
// or nil if none found.
func (m *ArticleChannel) ValidateAll() error {
	return m.validate(true)
}

func (m *ArticleChannel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return ArticleChannelMultiError(errors)
	}

	return nil
}

// ArticleChannelMultiError is an error wrapping multiple validation errors
// returned by ArticleChannel.ValidateAll() if the designated constraints
// aren't met.
type ArticleChannelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleChannelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleChannelMultiError) AllErrors() []error { return m }

// ArticleChannelValidationError is the validation error returned by
// ArticleChannel.Validate if the designated constraints aren't met.
type ArticleChannelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleChannelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleChannelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleChannelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleChannelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleChannelValidationError) ErrorName() string { return "ArticleChannelValidationError" }

// Error satisfies the builtin error interface
func (e ArticleChannelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticleChannel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleChannelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleChannelValidationError{}

// Validate checks the field values on GetArticleChannelResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArticleChannelResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleChannelResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleChannelRespMultiError, or nil if none found.
func (m *GetArticleChannelResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleChannelResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetChannels() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetArticleChannelRespValidationError{
						field:  fmt.Sprintf("Channels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetArticleChannelRespValidationError{
						field:  fmt.Sprintf("Channels[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetArticleChannelRespValidationError{
					field:  fmt.Sprintf("Channels[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetArticleChannelRespMultiError(errors)
	}

	return nil
}

// GetArticleChannelRespMultiError is an error wrapping multiple validation
// errors returned by GetArticleChannelResp.ValidateAll() if the designated
// constraints aren't met.
type GetArticleChannelRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleChannelRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleChannelRespMultiError) AllErrors() []error { return m }

// GetArticleChannelRespValidationError is the validation error returned by
// GetArticleChannelResp.Validate if the designated constraints aren't met.
type GetArticleChannelRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleChannelRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleChannelRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleChannelRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleChannelRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleChannelRespValidationError) ErrorName() string {
	return "GetArticleChannelRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleChannelRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleChannelResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleChannelRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleChannelRespValidationError{}

// Validate checks the field values on Cover with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Cover) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Cover with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CoverMultiError, or nil if none found.
func (m *Cover) ValidateAll() error {
	return m.validate(true)
}

func (m *Cover) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if len(errors) > 0 {
		return CoverMultiError(errors)
	}

	return nil
}

// CoverMultiError is an error wrapping multiple validation errors returned by
// Cover.ValidateAll() if the designated constraints aren't met.
type CoverMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CoverMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CoverMultiError) AllErrors() []error { return m }

// CoverValidationError is the validation error returned by Cover.Validate if
// the designated constraints aren't met.
type CoverValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CoverValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CoverValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CoverValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CoverValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CoverValidationError) ErrorName() string { return "CoverValidationError" }

// Error satisfies the builtin error interface
func (e CoverValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCover.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CoverValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CoverValidationError{}

// Validate checks the field values on AddArticleReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddArticleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddArticleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddArticleReqMultiError, or
// nil if none found.
func (m *AddArticleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AddArticleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Draft

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for ChannelId

	if all {
		switch v := interface{}(m.GetCover()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddArticleReqValidationError{
					field:  "Cover",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddArticleReqValidationError{
					field:  "Cover",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCover()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddArticleReqValidationError{
				field:  "Cover",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddArticleReqMultiError(errors)
	}

	return nil
}

// AddArticleReqMultiError is an error wrapping multiple validation errors
// returned by AddArticleReq.ValidateAll() if the designated constraints
// aren't met.
type AddArticleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddArticleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddArticleReqMultiError) AllErrors() []error { return m }

// AddArticleReqValidationError is the validation error returned by
// AddArticleReq.Validate if the designated constraints aren't met.
type AddArticleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddArticleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddArticleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddArticleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddArticleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddArticleReqValidationError) ErrorName() string { return "AddArticleReqValidationError" }

// Error satisfies the builtin error interface
func (e AddArticleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddArticleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddArticleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddArticleReqValidationError{}

// Validate checks the field values on AddArticleResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddArticleResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddArticleResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddArticleRespMultiError,
// or nil if none found.
func (m *AddArticleResp) ValidateAll() error {
	return m.validate(true)
}

func (m *AddArticleResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return AddArticleRespMultiError(errors)
	}

	return nil
}

// AddArticleRespMultiError is an error wrapping multiple validation errors
// returned by AddArticleResp.ValidateAll() if the designated constraints
// aren't met.
type AddArticleRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddArticleRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddArticleRespMultiError) AllErrors() []error { return m }

// AddArticleRespValidationError is the validation error returned by
// AddArticleResp.Validate if the designated constraints aren't met.
type AddArticleRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddArticleRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddArticleRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddArticleRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddArticleRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddArticleRespValidationError) ErrorName() string { return "AddArticleRespValidationError" }

// Error satisfies the builtin error interface
func (e AddArticleRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddArticleResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddArticleRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddArticleRespValidationError{}

// Validate checks the field values on GetArticleListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetArticleListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleListReqMultiError, or nil if none found.
func (m *GetArticleListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for ChannelId

	// no validation rules for BeginPubdate

	// no validation rules for EndPubdate

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetArticleListReqMultiError(errors)
	}

	return nil
}

// GetArticleListReqMultiError is an error wrapping multiple validation errors
// returned by GetArticleListReq.ValidateAll() if the designated constraints
// aren't met.
type GetArticleListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleListReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleListReqMultiError) AllErrors() []error { return m }

// GetArticleListReqValidationError is the validation error returned by
// GetArticleListReq.Validate if the designated constraints aren't met.
type GetArticleListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleListReqValidationError) ErrorName() string {
	return "GetArticleListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleListReqValidationError{}

// Validate checks the field values on ArticleInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ArticleInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArticleInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ArticleInfoMultiError, or
// nil if none found.
func (m *ArticleInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ArticleInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for CoverType

	// no validation rules for ChannelId

	// no validation rules for Status

	// no validation rules for AuthorId

	// no validation rules for ViewCount

	// no validation rules for LikeCount

	// no validation rules for CommentCount

	// no validation rules for IsTop

	// no validation rules for IsRecommend

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ArticleInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ArticleInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ArticleInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ArticleInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ArticleInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ArticleInfoValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ArticleInfoMultiError(errors)
	}

	return nil
}

// ArticleInfoMultiError is an error wrapping multiple validation errors
// returned by ArticleInfo.ValidateAll() if the designated constraints aren't met.
type ArticleInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArticleInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArticleInfoMultiError) AllErrors() []error { return m }

// ArticleInfoValidationError is the validation error returned by
// ArticleInfo.Validate if the designated constraints aren't met.
type ArticleInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArticleInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArticleInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArticleInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArticleInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArticleInfoValidationError) ErrorName() string { return "ArticleInfoValidationError" }

// Error satisfies the builtin error interface
func (e ArticleInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArticleInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArticleInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArticleInfoValidationError{}

// Validate checks the field values on GetArticleListResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArticleListResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleListResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleListRespMultiError, or nil if none found.
func (m *GetArticleListResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleListResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetArticleListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetArticleListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetArticleListRespValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetArticleListRespMultiError(errors)
	}

	return nil
}

// GetArticleListRespMultiError is an error wrapping multiple validation errors
// returned by GetArticleListResp.ValidateAll() if the designated constraints
// aren't met.
type GetArticleListRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleListRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleListRespMultiError) AllErrors() []error { return m }

// GetArticleListRespValidationError is the validation error returned by
// GetArticleListResp.Validate if the designated constraints aren't met.
type GetArticleListRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleListRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleListRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleListRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleListRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleListRespValidationError) ErrorName() string {
	return "GetArticleListRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleListRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleListResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleListRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleListRespValidationError{}

// Validate checks the field values on GetArticleByIdReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetArticleByIdReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleByIdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleByIdReqMultiError, or nil if none found.
func (m *GetArticleByIdReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleByIdReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Target

	if len(errors) > 0 {
		return GetArticleByIdReqMultiError(errors)
	}

	return nil
}

// GetArticleByIdReqMultiError is an error wrapping multiple validation errors
// returned by GetArticleByIdReq.ValidateAll() if the designated constraints
// aren't met.
type GetArticleByIdReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleByIdReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleByIdReqMultiError) AllErrors() []error { return m }

// GetArticleByIdReqValidationError is the validation error returned by
// GetArticleByIdReq.Validate if the designated constraints aren't met.
type GetArticleByIdReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleByIdReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleByIdReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleByIdReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleByIdReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleByIdReqValidationError) ErrorName() string {
	return "GetArticleByIdReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleByIdReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleByIdReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleByIdReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleByIdReqValidationError{}

// Validate checks the field values on GetArticleByIdResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetArticleByIdResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetArticleByIdResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetArticleByIdRespMultiError, or nil if none found.
func (m *GetArticleByIdResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetArticleByIdResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for CoverType

	// no validation rules for ChannelId

	// no validation rules for Status

	// no validation rules for AuthorId

	// no validation rules for ViewCount

	// no validation rules for LikeCount

	// no validation rules for CommentCount

	// no validation rules for IsTop

	// no validation rules for IsRecommend

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetArticleByIdRespValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetArticleByIdRespValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetArticleByIdRespValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetArticleByIdRespValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetArticleByIdRespValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetArticleByIdRespValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetArticleByIdRespMultiError(errors)
	}

	return nil
}

// GetArticleByIdRespMultiError is an error wrapping multiple validation errors
// returned by GetArticleByIdResp.ValidateAll() if the designated constraints
// aren't met.
type GetArticleByIdRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetArticleByIdRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetArticleByIdRespMultiError) AllErrors() []error { return m }

// GetArticleByIdRespValidationError is the validation error returned by
// GetArticleByIdResp.Validate if the designated constraints aren't met.
type GetArticleByIdRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetArticleByIdRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetArticleByIdRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetArticleByIdRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetArticleByIdRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetArticleByIdRespValidationError) ErrorName() string {
	return "GetArticleByIdRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetArticleByIdRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetArticleByIdResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetArticleByIdRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetArticleByIdRespValidationError{}

// Validate checks the field values on DeleteArticleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteArticleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteArticleReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteArticleReqMultiError, or nil if none found.
func (m *DeleteArticleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteArticleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Target

	if len(errors) > 0 {
		return DeleteArticleReqMultiError(errors)
	}

	return nil
}

// DeleteArticleReqMultiError is an error wrapping multiple validation errors
// returned by DeleteArticleReq.ValidateAll() if the designated constraints
// aren't met.
type DeleteArticleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteArticleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteArticleReqMultiError) AllErrors() []error { return m }

// DeleteArticleReqValidationError is the validation error returned by
// DeleteArticleReq.Validate if the designated constraints aren't met.
type DeleteArticleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteArticleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteArticleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteArticleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteArticleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteArticleReqValidationError) ErrorName() string { return "DeleteArticleReqValidationError" }

// Error satisfies the builtin error interface
func (e DeleteArticleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteArticleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteArticleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteArticleReqValidationError{}

// Validate checks the field values on DeleteArticleResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteArticleResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteArticleResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteArticleRespMultiError, or nil if none found.
func (m *DeleteArticleResp) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteArticleResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteArticleRespMultiError(errors)
	}

	return nil
}

// DeleteArticleRespMultiError is an error wrapping multiple validation errors
// returned by DeleteArticleResp.ValidateAll() if the designated constraints
// aren't met.
type DeleteArticleRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteArticleRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteArticleRespMultiError) AllErrors() []error { return m }

// DeleteArticleRespValidationError is the validation error returned by
// DeleteArticleResp.Validate if the designated constraints aren't met.
type DeleteArticleRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteArticleRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteArticleRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteArticleRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteArticleRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteArticleRespValidationError) ErrorName() string {
	return "DeleteArticleRespValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteArticleRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteArticleResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteArticleRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteArticleRespValidationError{}

// Validate checks the field values on UpdateArticleByIdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateArticleByIdReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateArticleByIdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateArticleByIdReqMultiError, or nil if none found.
func (m *UpdateArticleByIdReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateArticleByIdReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Target

	// no validation rules for Draft

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for ChannelId

	if all {
		switch v := interface{}(m.GetCover()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateArticleByIdReqValidationError{
					field:  "Cover",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateArticleByIdReqValidationError{
					field:  "Cover",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCover()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateArticleByIdReqValidationError{
				field:  "Cover",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateArticleByIdReqMultiError(errors)
	}

	return nil
}

// UpdateArticleByIdReqMultiError is an error wrapping multiple validation
// errors returned by UpdateArticleByIdReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateArticleByIdReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateArticleByIdReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateArticleByIdReqMultiError) AllErrors() []error { return m }

// UpdateArticleByIdReqValidationError is the validation error returned by
// UpdateArticleByIdReq.Validate if the designated constraints aren't met.
type UpdateArticleByIdReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateArticleByIdReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateArticleByIdReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateArticleByIdReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateArticleByIdReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateArticleByIdReqValidationError) ErrorName() string {
	return "UpdateArticleByIdReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateArticleByIdReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateArticleByIdReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateArticleByIdReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateArticleByIdReqValidationError{}

// Validate checks the field values on UpdateArticleByIdResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateArticleByIdResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateArticleByIdResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateArticleByIdRespMultiError, or nil if none found.
func (m *UpdateArticleByIdResp) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateArticleByIdResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateArticleByIdRespMultiError(errors)
	}

	return nil
}

// UpdateArticleByIdRespMultiError is an error wrapping multiple validation
// errors returned by UpdateArticleByIdResp.ValidateAll() if the designated
// constraints aren't met.
type UpdateArticleByIdRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateArticleByIdRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateArticleByIdRespMultiError) AllErrors() []error { return m }

// UpdateArticleByIdRespValidationError is the validation error returned by
// UpdateArticleByIdResp.Validate if the designated constraints aren't met.
type UpdateArticleByIdRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateArticleByIdRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateArticleByIdRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateArticleByIdRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateArticleByIdRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateArticleByIdRespValidationError) ErrorName() string {
	return "UpdateArticleByIdRespValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateArticleByIdRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateArticleByIdResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateArticleByIdRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateArticleByIdRespValidationError{}
