// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/article/v1/article.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArticleChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleChannelReq) Reset() {
	*x = GetArticleChannelReq{}
	mi := &file_api_article_v1_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleChannelReq) ProtoMessage() {}

func (x *GetArticleChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleChannelReq.ProtoReflect.Descriptor instead.
func (*GetArticleChannelReq) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{0}
}

type ArticleChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleChannel) Reset() {
	*x = ArticleChannel{}
	mi := &file_api_article_v1_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleChannel) ProtoMessage() {}

func (x *ArticleChannel) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleChannel.ProtoReflect.Descriptor instead.
func (*ArticleChannel) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleChannel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetArticleChannelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ArticleChannel      `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleChannelResp) Reset() {
	*x = GetArticleChannelResp{}
	mi := &file_api_article_v1_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleChannelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleChannelResp) ProtoMessage() {}

func (x *GetArticleChannelResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleChannelResp.ProtoReflect.Descriptor instead.
func (*GetArticleChannelResp) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleChannelResp) GetChannels() []*ArticleChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type Cover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []string               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"` // 封面图片
	Type          int64                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cover) Reset() {
	*x = Cover{}
	mi := &file_api_article_v1_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cover) ProtoMessage() {}

func (x *Cover) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cover.ProtoReflect.Descriptor instead.
func (*Cover) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *Cover) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Cover) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type AddArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Draft         string                 `protobuf:"bytes,1,opt,name=draft,proto3" json:"draft,omitempty"`                           // query 参数，对应 ?draft=xxx
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                           // body 参数
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                       // body 参数
	ChannelId     int64                  `protobuf:"varint,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // body 参数
	Cover         *Cover                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticleReq) Reset() {
	*x = AddArticleReq{}
	mi := &file_api_article_v1_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleReq) ProtoMessage() {}

func (x *AddArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleReq.ProtoReflect.Descriptor instead.
func (*AddArticleReq) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{4}
}

func (x *AddArticleReq) GetDraft() string {
	if x != nil {
		return x.Draft
	}
	return ""
}

func (x *AddArticleReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddArticleReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddArticleReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *AddArticleReq) GetCover() *Cover {
	if x != nil {
		return x.Cover
	}
	return nil
}

type AddArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddArticleResp) Reset() {
	*x = AddArticleResp{}
	mi := &file_api_article_v1_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleResp) ProtoMessage() {}

func (x *AddArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleResp.ProtoReflect.Descriptor instead.
func (*AddArticleResp) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{5}
}

func (x *AddArticleResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ChannelId     int64                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	BeginPubdate  string                 `protobuf:"bytes,3,opt,name=begin_pubdate,json=beginPubdate,proto3" json:"begin_pubdate,omitempty"`
	EndPubdate    string                 `protobuf:"bytes,4,opt,name=end_pubdate,json=endPubdate,proto3" json:"end_pubdate,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleListReq) Reset() {
	*x = GetArticleListReq{}
	mi := &file_api_article_v1_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListReq) ProtoMessage() {}

func (x *GetArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListReq.ProtoReflect.Descriptor instead.
func (*GetArticleListReq) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{6}
}

func (x *GetArticleListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetArticleListReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GetArticleListReq) GetBeginPubdate() string {
	if x != nil {
		return x.BeginPubdate
	}
	return ""
}

func (x *GetArticleListReq) GetEndPubdate() string {
	if x != nil {
		return x.EndPubdate
	}
	return ""
}

func (x *GetArticleListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetArticleListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ArticleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 文章Id
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                     // 文章标题
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                 // 文章内容
	CoverType     int64                  `protobuf:"varint,4,opt,name=cover_type,json=coverType,proto3" json:"cover_type,omitempty"`           // 封面类型：1-无图，2-单图，3-多图
	CoverImages   []string               `protobuf:"bytes,5,rep,name=cover_images,json=coverImages,proto3" json:"cover_images,omitempty"`      // 封面图片地址数组
	ChannelId     int64                  `protobuf:"varint,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`           // 频道Id
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                  // 文章状态：0-草稿，1-已发布，2-已删除
	AuthorId      int64                  `protobuf:"varint,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`              // 作者Id
	ViewCount     int64                  `protobuf:"varint,9,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`           // 阅读量
	LikeCount     int64                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数
	CommentCount  int64                  `protobuf:"varint,11,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数
	IsTop         int64                  `protobuf:"varint,12,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                      // 是否置顶：0-否，1-是
	IsRecommend   int64                  `protobuf:"varint,13,opt,name=is_recommend,json=isRecommend,proto3" json:"is_recommend,omitempty"`    // 是否推荐：0-否，1-是
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleInfo) Reset() {
	*x = ArticleInfo{}
	mi := &file_api_article_v1_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleInfo) ProtoMessage() {}

func (x *ArticleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleInfo.ProtoReflect.Descriptor instead.
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{7}
}

func (x *ArticleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleInfo) GetCoverType() int64 {
	if x != nil {
		return x.CoverType
	}
	return 0
}

func (x *ArticleInfo) GetCoverImages() []string {
	if x != nil {
		return x.CoverImages
	}
	return nil
}

func (x *ArticleInfo) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ArticleInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ArticleInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ArticleInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ArticleInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ArticleInfo) GetIsTop() int64 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *ArticleInfo) GetIsRecommend() int64 {
	if x != nil {
		return x.IsRecommend
	}
	return 0
}

func (x *ArticleInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArticleInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetArticleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*ArticleInfo         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleListResp) Reset() {
	*x = GetArticleListResp{}
	mi := &file_api_article_v1_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListResp) ProtoMessage() {}

func (x *GetArticleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListResp.ProtoReflect.Descriptor instead.
func (*GetArticleListResp) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetArticleListResp) GetList() []*ArticleInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetArticleByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int64                  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIdReq) Reset() {
	*x = GetArticleByIdReq{}
	mi := &file_api_article_v1_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIdReq) ProtoMessage() {}

func (x *GetArticleByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIdReq.ProtoReflect.Descriptor instead.
func (*GetArticleByIdReq) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{9}
}

func (x *GetArticleByIdReq) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

type GetArticleByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 文章Id
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                     // 文章标题
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                 // 文章内容
	CoverType     int64                  `protobuf:"varint,4,opt,name=cover_type,json=coverType,proto3" json:"cover_type,omitempty"`           // 封面类型：1-无图，2-单图，3-多图
	CoverImages   []string               `protobuf:"bytes,5,rep,name=cover_images,json=coverImages,proto3" json:"cover_images,omitempty"`      // 封面图片地址数组
	ChannelId     int64                  `protobuf:"varint,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`           // 频道Id
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                  // 文章状态：0-草稿，1-已发布，2-已删除
	AuthorId      int64                  `protobuf:"varint,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`              // 作者Id
	ViewCount     int64                  `protobuf:"varint,9,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`           // 阅读量
	LikeCount     int64                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`          // 点赞数
	CommentCount  int64                  `protobuf:"varint,11,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // 评论数
	IsTop         int64                  `protobuf:"varint,12,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`                      // 是否置顶：0-否，1-是
	IsRecommend   int64                  `protobuf:"varint,13,opt,name=is_recommend,json=isRecommend,proto3" json:"is_recommend,omitempty"`    // 是否推荐：0-否，1-是
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIdResp) Reset() {
	*x = GetArticleByIdResp{}
	mi := &file_api_article_v1_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIdResp) ProtoMessage() {}

func (x *GetArticleByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIdResp.ProtoReflect.Descriptor instead.
func (*GetArticleByIdResp) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{10}
}

func (x *GetArticleByIdResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetArticleByIdResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetArticleByIdResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetArticleByIdResp) GetCoverType() int64 {
	if x != nil {
		return x.CoverType
	}
	return 0
}

func (x *GetArticleByIdResp) GetCoverImages() []string {
	if x != nil {
		return x.CoverImages
	}
	return nil
}

func (x *GetArticleByIdResp) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GetArticleByIdResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetArticleByIdResp) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *GetArticleByIdResp) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *GetArticleByIdResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *GetArticleByIdResp) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *GetArticleByIdResp) GetIsTop() int64 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *GetArticleByIdResp) GetIsRecommend() int64 {
	if x != nil {
		return x.IsRecommend
	}
	return 0
}

func (x *GetArticleByIdResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetArticleByIdResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int64                  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReq) Reset() {
	*x = DeleteArticleReq{}
	mi := &file_api_article_v1_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReq) ProtoMessage() {}

func (x *DeleteArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReq.ProtoReflect.Descriptor instead.
func (*DeleteArticleReq) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteArticleReq) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

type DeleteArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResp) Reset() {
	*x = DeleteArticleResp{}
	mi := &file_api_article_v1_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResp) ProtoMessage() {}

func (x *DeleteArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResp.ProtoReflect.Descriptor instead.
func (*DeleteArticleResp) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{12}
}

type UpdateArticleByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int64                  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Draft         string                 `protobuf:"bytes,2,opt,name=draft,proto3" json:"draft,omitempty"`                           // query 参数，对应 ?draft=xxx
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                           // body 参数
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                       // body 参数
	ChannelId     int64                  `protobuf:"varint,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // body 参数
	Cover         *Cover                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleByIdReq) Reset() {
	*x = UpdateArticleByIdReq{}
	mi := &file_api_article_v1_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleByIdReq) ProtoMessage() {}

func (x *UpdateArticleByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleByIdReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleByIdReq) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateArticleByIdReq) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *UpdateArticleByIdReq) GetDraft() string {
	if x != nil {
		return x.Draft
	}
	return ""
}

func (x *UpdateArticleByIdReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleByIdReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateArticleByIdReq) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *UpdateArticleByIdReq) GetCover() *Cover {
	if x != nil {
		return x.Cover
	}
	return nil
}

type UpdateArticleByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleByIdResp) Reset() {
	*x = UpdateArticleByIdResp{}
	mi := &file_api_article_v1_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleByIdResp) ProtoMessage() {}

func (x *UpdateArticleByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_article_v1_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleByIdResp.ProtoReflect.Descriptor instead.
func (*UpdateArticleByIdResp) Descriptor() ([]byte, []int) {
	return file_api_article_v1_article_proto_rawDescGZIP(), []int{14}
}

var File_api_article_v1_article_proto protoreflect.FileDescriptor

const file_api_article_v1_article_proto_rawDesc = "" +
	"\n" +
	"\x1capi/article/v1/article.proto\x12\n" +
	"article.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x16\n" +
	"\x14GetArticleChannelReq\"4\n" +
	"\x0eArticleChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"O\n" +
	"\x15GetArticleChannelResp\x126\n" +
	"\bchannels\x18\x01 \x03(\v2\x1a.article.v1.ArticleChannelR\bchannels\"3\n" +
	"\x05Cover\x12\x16\n" +
	"\x06images\x18\x01 \x03(\tR\x06images\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x03R\x04type\"\x9d\x01\n" +
	"\rAddArticleReq\x12\x14\n" +
	"\x05draft\x18\x01 \x01(\tR\x05draft\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\x03R\tchannelId\x12'\n" +
	"\x05cover\x18\x05 \x01(\v2\x11.article.v1.CoverR\x05cover\" \n" +
	"\x0eAddArticleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc1\x01\n" +
	"\x11GetArticleListReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x03R\tchannelId\x12#\n" +
	"\rbegin_pubdate\x18\x03 \x01(\tR\fbeginPubdate\x12\x1f\n" +
	"\vend_pubdate\x18\x04 \x01(\tR\n" +
	"endPubdate\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSize\"\xf6\x03\n" +
	"\vArticleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"cover_type\x18\x04 \x01(\x03R\tcoverType\x12!\n" +
	"\fcover_images\x18\x05 \x03(\tR\vcoverImages\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\x03R\tchannelId\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"view_count\x18\t \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\v \x01(\x03R\fcommentCount\x12\x15\n" +
	"\x06is_top\x18\f \x01(\x03R\x05isTop\x12!\n" +
	"\fis_recommend\x18\r \x01(\x03R\visRecommend\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"W\n" +
	"\x12GetArticleListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12+\n" +
	"\x04list\x18\x02 \x03(\v2\x17.article.v1.ArticleInfoR\x04list\"+\n" +
	"\x11GetArticleByIdReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x03R\x06target\"\xfd\x03\n" +
	"\x12GetArticleByIdResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"cover_type\x18\x04 \x01(\x03R\tcoverType\x12!\n" +
	"\fcover_images\x18\x05 \x03(\tR\vcoverImages\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x06 \x01(\x03R\tchannelId\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"view_count\x18\t \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\v \x01(\x03R\fcommentCount\x12\x15\n" +
	"\x06is_top\x18\f \x01(\x03R\x05isTop\x12!\n" +
	"\fis_recommend\x18\r \x01(\x03R\visRecommend\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"*\n" +
	"\x10DeleteArticleReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x03R\x06target\"\x13\n" +
	"\x11DeleteArticleResp\"\xbc\x01\n" +
	"\x14UpdateArticleByIdReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x03R\x06target\x12\x14\n" +
	"\x05draft\x18\x02 \x01(\tR\x05draft\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\x03R\tchannelId\x12'\n" +
	"\x05cover\x18\x06 \x01(\v2\x11.article.v1.CoverR\x05cover\"\x17\n" +
	"\x15UpdateArticleByIdResp2\xa6\x05\n" +
	"\aArticle\x12n\n" +
	"\x11GetArticleChannel\x12 .article.v1.GetArticleChannelReq\x1a!.article.v1.GetArticleChannelResp\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/channels\x12_\n" +
	"\n" +
	"AddArticle\x12\x19.article.v1.AddArticleReq\x1a\x1a.article.v1.AddArticleResp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/mp/articles\x12h\n" +
	"\x0eGetArticleList\x12\x1d.article.v1.GetArticleListReq\x1a\x1e.article.v1.GetArticleListResp\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/mp/articles\x12q\n" +
	"\x0eGetArticleById\x12\x1d.article.v1.GetArticleByIdReq\x1a\x1e.article.v1.GetArticleByIdResp\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/mp/articles/{target}\x12}\n" +
	"\x11UpdateArticleById\x12 .article.v1.UpdateArticleByIdReq\x1a!.article.v1.UpdateArticleByIdResp\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/mp/articles/{target}\x12n\n" +
	"\rDeleteArticle\x12\x1c.article.v1.DeleteArticleReq\x1a\x1d.article.v1.DeleteArticleResp\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/mp/articles/{target}B\x1fZ\x1djike_server/api/article/v1;v1b\x06proto3"

var (
	file_api_article_v1_article_proto_rawDescOnce sync.Once
	file_api_article_v1_article_proto_rawDescData []byte
)

func file_api_article_v1_article_proto_rawDescGZIP() []byte {
	file_api_article_v1_article_proto_rawDescOnce.Do(func() {
		file_api_article_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_article_v1_article_proto_rawDesc), len(file_api_article_v1_article_proto_rawDesc)))
	})
	return file_api_article_v1_article_proto_rawDescData
}

var file_api_article_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_article_v1_article_proto_goTypes = []any{
	(*GetArticleChannelReq)(nil),  // 0: article.v1.GetArticleChannelReq
	(*ArticleChannel)(nil),        // 1: article.v1.ArticleChannel
	(*GetArticleChannelResp)(nil), // 2: article.v1.GetArticleChannelResp
	(*Cover)(nil),                 // 3: article.v1.Cover
	(*AddArticleReq)(nil),         // 4: article.v1.AddArticleReq
	(*AddArticleResp)(nil),        // 5: article.v1.AddArticleResp
	(*GetArticleListReq)(nil),     // 6: article.v1.GetArticleListReq
	(*ArticleInfo)(nil),           // 7: article.v1.ArticleInfo
	(*GetArticleListResp)(nil),    // 8: article.v1.GetArticleListResp
	(*GetArticleByIdReq)(nil),     // 9: article.v1.GetArticleByIdReq
	(*GetArticleByIdResp)(nil),    // 10: article.v1.GetArticleByIdResp
	(*DeleteArticleReq)(nil),      // 11: article.v1.DeleteArticleReq
	(*DeleteArticleResp)(nil),     // 12: article.v1.DeleteArticleResp
	(*UpdateArticleByIdReq)(nil),  // 13: article.v1.UpdateArticleByIdReq
	(*UpdateArticleByIdResp)(nil), // 14: article.v1.UpdateArticleByIdResp
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_api_article_v1_article_proto_depIdxs = []int32{
	1,  // 0: article.v1.GetArticleChannelResp.channels:type_name -> article.v1.ArticleChannel
	3,  // 1: article.v1.AddArticleReq.cover:type_name -> article.v1.Cover
	15, // 2: article.v1.ArticleInfo.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: article.v1.ArticleInfo.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 4: article.v1.GetArticleListResp.list:type_name -> article.v1.ArticleInfo
	15, // 5: article.v1.GetArticleByIdResp.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: article.v1.GetArticleByIdResp.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 7: article.v1.UpdateArticleByIdReq.cover:type_name -> article.v1.Cover
	0,  // 8: article.v1.Article.GetArticleChannel:input_type -> article.v1.GetArticleChannelReq
	4,  // 9: article.v1.Article.AddArticle:input_type -> article.v1.AddArticleReq
	6,  // 10: article.v1.Article.GetArticleList:input_type -> article.v1.GetArticleListReq
	9,  // 11: article.v1.Article.GetArticleById:input_type -> article.v1.GetArticleByIdReq
	13, // 12: article.v1.Article.UpdateArticleById:input_type -> article.v1.UpdateArticleByIdReq
	11, // 13: article.v1.Article.DeleteArticle:input_type -> article.v1.DeleteArticleReq
	2,  // 14: article.v1.Article.GetArticleChannel:output_type -> article.v1.GetArticleChannelResp
	5,  // 15: article.v1.Article.AddArticle:output_type -> article.v1.AddArticleResp
	8,  // 16: article.v1.Article.GetArticleList:output_type -> article.v1.GetArticleListResp
	10, // 17: article.v1.Article.GetArticleById:output_type -> article.v1.GetArticleByIdResp
	14, // 18: article.v1.Article.UpdateArticleById:output_type -> article.v1.UpdateArticleByIdResp
	12, // 19: article.v1.Article.DeleteArticle:output_type -> article.v1.DeleteArticleResp
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_article_v1_article_proto_init() }
func file_api_article_v1_article_proto_init() {
	if File_api_article_v1_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_article_v1_article_proto_rawDesc), len(file_api_article_v1_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_article_v1_article_proto_goTypes,
		DependencyIndexes: file_api_article_v1_article_proto_depIdxs,
		MessageInfos:      file_api_article_v1_article_proto_msgTypes,
	}.Build()
	File_api_article_v1_article_proto = out.File
	file_api_article_v1_article_proto_goTypes = nil
	file_api_article_v1_article_proto_depIdxs = nil
}
