// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.20.3
// source: api/article/v1/article.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationArticleAddArticle = "/article.v1.Article/AddArticle"
const OperationArticleDeleteArticle = "/article.v1.Article/DeleteArticle"
const OperationArticleGetArticleById = "/article.v1.Article/GetArticleById"
const OperationArticleGetArticleChannel = "/article.v1.Article/GetArticleChannel"
const OperationArticleGetArticleList = "/article.v1.Article/GetArticleList"
const OperationArticleUpdateArticleById = "/article.v1.Article/UpdateArticleById"

type ArticleHTTPServer interface {
	AddArticle(context.Context, *AddArticleReq) (*AddArticleResp, error)
	DeleteArticle(context.Context, *DeleteArticleReq) (*DeleteArticleResp, error)
	GetArticleById(context.Context, *GetArticleByIdReq) (*GetArticleByIdResp, error)
	GetArticleChannel(context.Context, *GetArticleChannelReq) (*GetArticleChannelResp, error)
	GetArticleList(context.Context, *GetArticleListReq) (*GetArticleListResp, error)
	UpdateArticleById(context.Context, *UpdateArticleByIdReq) (*UpdateArticleByIdResp, error)
}

func RegisterArticleHTTPServer(s *http.Server, srv ArticleHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/channels", _Article_GetArticleChannel0_HTTP_Handler(srv))
	r.POST("/v1/mp/articles", _Article_AddArticle0_HTTP_Handler(srv))
	r.GET("/v1/mp/articles", _Article_GetArticleList0_HTTP_Handler(srv))
	r.GET("/v1/mp/articles/{target}", _Article_GetArticleById0_HTTP_Handler(srv))
	r.PUT("/v1/mp/articles/{target}", _Article_UpdateArticleById0_HTTP_Handler(srv))
	r.DELETE("/v1/mp/articles/{target}", _Article_DeleteArticle0_HTTP_Handler(srv))
}

func _Article_GetArticleChannel0_HTTP_Handler(srv ArticleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleChannelReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleGetArticleChannel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticleChannel(ctx, req.(*GetArticleChannelReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetArticleChannelResp)
		return ctx.Result(200, reply)
	}
}

func _Article_AddArticle0_HTTP_Handler(srv ArticleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddArticleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleAddArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddArticle(ctx, req.(*AddArticleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddArticleResp)
		return ctx.Result(200, reply)
	}
}

func _Article_GetArticleList0_HTTP_Handler(srv ArticleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleGetArticleList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticleList(ctx, req.(*GetArticleListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetArticleListResp)
		return ctx.Result(200, reply)
	}
}

func _Article_GetArticleById0_HTTP_Handler(srv ArticleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleByIdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleGetArticleById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticleById(ctx, req.(*GetArticleByIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetArticleByIdResp)
		return ctx.Result(200, reply)
	}
}

func _Article_UpdateArticleById0_HTTP_Handler(srv ArticleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateArticleByIdReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleUpdateArticleById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateArticleById(ctx, req.(*UpdateArticleByIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateArticleByIdResp)
		return ctx.Result(200, reply)
	}
}

func _Article_DeleteArticle0_HTTP_Handler(srv ArticleHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteArticleReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleDeleteArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteArticle(ctx, req.(*DeleteArticleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteArticleResp)
		return ctx.Result(200, reply)
	}
}

type ArticleHTTPClient interface {
	AddArticle(ctx context.Context, req *AddArticleReq, opts ...http.CallOption) (rsp *AddArticleResp, err error)
	DeleteArticle(ctx context.Context, req *DeleteArticleReq, opts ...http.CallOption) (rsp *DeleteArticleResp, err error)
	GetArticleById(ctx context.Context, req *GetArticleByIdReq, opts ...http.CallOption) (rsp *GetArticleByIdResp, err error)
	GetArticleChannel(ctx context.Context, req *GetArticleChannelReq, opts ...http.CallOption) (rsp *GetArticleChannelResp, err error)
	GetArticleList(ctx context.Context, req *GetArticleListReq, opts ...http.CallOption) (rsp *GetArticleListResp, err error)
	UpdateArticleById(ctx context.Context, req *UpdateArticleByIdReq, opts ...http.CallOption) (rsp *UpdateArticleByIdResp, err error)
}

type ArticleHTTPClientImpl struct {
	cc *http.Client
}

func NewArticleHTTPClient(client *http.Client) ArticleHTTPClient {
	return &ArticleHTTPClientImpl{client}
}

func (c *ArticleHTTPClientImpl) AddArticle(ctx context.Context, in *AddArticleReq, opts ...http.CallOption) (*AddArticleResp, error) {
	var out AddArticleResp
	pattern := "/v1/mp/articles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleAddArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArticleHTTPClientImpl) DeleteArticle(ctx context.Context, in *DeleteArticleReq, opts ...http.CallOption) (*DeleteArticleResp, error) {
	var out DeleteArticleResp
	pattern := "/v1/mp/articles/{target}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleDeleteArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArticleHTTPClientImpl) GetArticleById(ctx context.Context, in *GetArticleByIdReq, opts ...http.CallOption) (*GetArticleByIdResp, error) {
	var out GetArticleByIdResp
	pattern := "/v1/mp/articles/{target}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleGetArticleById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArticleHTTPClientImpl) GetArticleChannel(ctx context.Context, in *GetArticleChannelReq, opts ...http.CallOption) (*GetArticleChannelResp, error) {
	var out GetArticleChannelResp
	pattern := "/v1/channels"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleGetArticleChannel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArticleHTTPClientImpl) GetArticleList(ctx context.Context, in *GetArticleListReq, opts ...http.CallOption) (*GetArticleListResp, error) {
	var out GetArticleListResp
	pattern := "/v1/mp/articles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleGetArticleList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ArticleHTTPClientImpl) UpdateArticleById(ctx context.Context, in *UpdateArticleByIdReq, opts ...http.CallOption) (*UpdateArticleByIdResp, error) {
	var out UpdateArticleByIdResp
	pattern := "/v1/mp/articles/{target}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleUpdateArticleById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
